import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-toastify/dist/ReactToastify.css";
import 'leaflet/dist/leaflet.css';
import {Inter} from 'next/font/google';
// import HeaderMenuComponent from "@/ui/Navigation/header/headerMenuComponent";
import Header from "@/ui/Navigation/header/header";
import Footer from "@/ui/Navigation/footer/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">

        <body className={inter.className}>
        <Header />
        {children}
        <Footer/>
        </body>
        </html>
    );
}
